---
name: Test 
on:
  workflow_dispatch:
    
jobs:
  validate-data:
    environment: test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate secrets
        run: |
          echo ${{secrets.LDAP_SECURITY_PRINCIPAL}} | sed 's/./& /g'
          
      - name: ansible test | Ansible
        shell: bash
        run: |
          echo 'ansible_test'
          ansible-playbook jinja_regex.yml -i ts_host --flush-cache \
            -e "{'ldap_security_principal':${{ 'secrets.LDAP_SECURITY_PRINCIPAL'}}}" \